### ISSUE TITLE
Serialized beans have extra parameters in JSON

### ISSUE THREAD

**Issue by craigwblake** [FasterXML/jackson-module-mrbean#20]
It appears that when serializing beans that were created with the MrBean module, the output JSON has every property duplicated with a leading underscore.  Here's a test case which reproduces the problem:

https://github.com/craigwblake/mrbean-test

The failure is this:

Failed tests:   testBean(com.gses.config.ParserTest): expected:<{"[field": ]"testing"}> but was:<{"[_field":"testing","field":]"testing"}>

**Comment by cowtowncoder** [comment]
That would definitely be wrong. Thank you for reporting this.

**Comment by craigwblake** [comment]
Awesome, thanks for the fast fix!

**Comment by cowtowncoder** [comment]
Thanks for reporting it -- I can't believe such an obvious problem wasn't reported earlier... I guess most use cases just involved deserialization.

FWIW, the underlying problem is two-fold:

1. Backing fields were named `_property`, AND
2. Fields were create as `public` and were visible for serialization

I changed both, although just changing visibility could also have worked.

**Comment by rethwischk** [comment]
This problem remains in MrBean 2.7.4.

**Comment by cowtowncoder** [comment]
@rethwischk If you still see a similar problem, please file a new issue with reproduction. Also make sure to test with latest 2.7 patch (2.7.7) as sometimes there are relevant fixes.
